{% set name = "potentials" %}
{% set version = "0.3.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: be4acd5517fd9ed612a5ff275e60261a373eb10e22165962b181ddf6cfae42fd

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<=37 or python_impl == 'pypy']

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - xmltodict
    - unidecode
    - datamodeldict
    - numpy
    - matplotlib-base
    - pandas
    - cdcs
    - requests
    - habanero
    - bibtexparser
    - ipython
    - ipywidgets
    - scipy
    - importlib_resources
    - lxml
    - yabadaba >=0.2.1
    - setuptools >=60

test:
  imports:
    - potentials
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/potentials
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: API for accessing the NIST Interatomic Potentials Repository.

  description: |
    The potentials package provides a Python-based interface to the content
    on the NIST Interatomic Potentials Repository. The package directly
    interacts with the underlying database at https://potentials.nist.gov/
    allowing for the hosted interatomic potentials to be searched and explored.
  doc_url: https://github.com/usnistgov/potentials
  dev_url: https://github.com/usnistgov/potentials

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
