{% set name = "potentials" %}
{% set version = "0.3.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5443c66b75a9f81dcab5eadf0395c68da0dfeac200912493d0659d7aa689704d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [py<=37 or python_impl == 'pypy']

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pip
    - xmltodict
    - unidecode
    - datamodeldict
    - numpy
    - matplotlib-base
    - pandas
    - requests
    - habanero
    - bibtexparser
    - cdcs =0.1.5
    - ipython
    - ipywidgets
    - scipy
    - importlib_resources
    - lxml
    - yabadaba
    - setuptools >=60

test:
  imports:
    - potentials
  commands:
    - pip check

about:
  home: https://github.com/usnistgov/potentials
  license: NIST-PD
  license_file: LICENSE.TXT
  summary: API for accessing the NIST Interatomic Potentials Repository.

  description: |
    The potentials package provides a Python-based interface to the content
    on the NIST Interatomic Potentials Repository. The package directly
    interacts with the underlying database at https://potentials.nist.gov/
    allowing for the hosted interatomic potentials to be searched and explored.
  doc_url: https://github.com/usnistgov/potentials
  dev_url: https://github.com/usnistgov/potentials

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
