{% set name = "potentials" %}
{% set version = "0.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 4564d3b3c83635a69da7a8d4ea15cd28452bb8b9f1be726961de3f3380a5cbe7

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  skip: true  # [py2k]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - xmltodict
    - datamodeldict
    - numpy
    - matplotlib
    - pandas
    - requests
    - habanero
    - bibtexparser
    - cdcs
    - ipython

test:
  imports:
    - potentials

about:
  home: https://github.com/usnistgov/potentials
  license: OTHER
  license_family: OTHER
  license_file: LICENSE.TXT
  summary: 'Alternative host of Interatomic Potentials Repository content'

  description: |
    Potentials provides a lightweight database of interatomic potentials 
    and force fields. Right now, the database contains listings for the 
    potentials stored in the NIST Interatomic Potentials Repository, as 
    well as about 75% of OpenKIM models.
  doc_url: https://github.com/usnistgov/potentials
  dev_url: https://github.com/usnistgov/potentials

extra:
  recipe-maintainers:
    - jan-janssen
    - lmhale99
